#cloud-config
package_update: true
#package_upgrade: true
packages:
  - ganglia-monitor
  - ganglia-modules-linux
runcmd:
  - ["cd","/home/ubuntu"]
  - ["git","clone","https://github.com/cgeroux/python-config-ganglia.git"]
  - ["./python-config-ganglia/configure.py","--master-ip","MASTERIP"]
  #note that the master-ip will need to be replaced, this could be done in the
  #master cloud init file after openstack_trigger has been setup
  
